FROM debian:bookworm-slim@sha256:67b30a61dc87758f0caf819646104f29ecbda97d920aaf5edc834128ac8493d3

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        iproute2 \
        python3 \
        python3-libtorrent && \
    rm -rf /var/lib/apt/lists/*

COPY peer.py /usr/local/bin/libtorrent-lab-peer

ENTRYPOINT ["python3", "/usr/local/bin/libtorrent-lab-peer"]
